// Generated by CoffeeScript 2.5.1
(function() {
  this.PopupWindow = (function() {
    var attributes;

    class PopupWindow {
      constructor(url1, attrs = {}) {
        this.url = url1;
        if (typeof url === "undefined" || url === null) {
          throw new Error('A url is required to create a popup');
        }
        $.extend(attributes, attrs);
        this.title = attributes.title;
        this.windowHeight = attributes.windowHeight;
        this.windowWidth = attributes.windowWidth;
        this.left = (screen.width / 2) - (this.windowWidth / 2);
        this.top = (screen.height / 2) - (this.windowHeight / 2);
        if (attributes.openOnCreate) {
          this.open();
        }
      }

      open() {
        return window.open(this.url, this.title, `toolbar=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no, width=${this.windowWidth}, height=${this.windowHeight}, top=${this.top}, left=${this.left}`);
      }

    };

    attributes = {
      title: "Popup Window Title",
      windowHeight: 600,
      windowWidth: 600,
      openOnCreate: true
    };

    return PopupWindow;

  }).call(this);

}).call(this);
